constants:
  ucheck-url: https://ucheck.utoronto.ca/questionnaire?org=22f9f13e-e281-4688-9d95-324d4ae4e43b&pt=21b5c4ae-c555-4dbf-a184-7f31bd7fea6b
  elements:
    abs-xpath:
      button:
        ucheck-submit: /html/body/div[1]/div/div/div/div[2]/main/div/div/div/div/div/button
      input:
        utorid-user: /html/body/div/div/div[1]/div[2]/form/div[1]/input
        utorid-pass: /html/body/div/div/div[1]/div[2]/form/div[2]/input
        ucheck-forms:
          - /html/body/div[1]/div/div/div/div[2]/main/div/div/div/div/form/div[6]/div/div/div/div/div/div/div/div/fieldset/label[2]/input
          - /html/body/div[1]/div/div/div/div[2]/main/div/div/div/div/form/div[8]/div/div/div/div/div/div/div/div/fieldset/label[1]/input
          - /html/body/div[1]/div/div/div/div[2]/main/div/div/div/div/form/div[10]/div/div/div/div/div/div/div/div/fieldset/label[1]/input
          - /html/body/div[1]/div/div/div/div[2]/main/div/div/div/div/form/div[12]/div/div/div/div/div/div/div/div/fieldset/label[1]/input
          - /html/body/div[1]/div/div/div/div[2]/main/div/div/div/div/form/div[14]/div/div/div/div/div/div/div/div/fieldset/label[1]/input
          - /html/body/div[1]/div/div/div/div[2]/main/div/div/div/div/form/div[16]/div/div/div/div/div/div/div/div/fieldset/label[1]/input
      p:
        invalid-utorid-login: /html/body/div/div/div[1]/div[2]/section[1]/p
  keywords:
    contains:
      invalid-utorid-login:
        - user login: cannot be identified
        - password: entered was incorrect
